# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: base58 0.2.3 ruby lib

Gem::Specification.new do |s|
  s.name = "base58".freeze
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Douglas F Shearer".freeze]
  s.date = "2018-05-16"
  s.description = "Base58 is a Ruby library for converting ints or binaries to and from base58.".freeze
  s.email = "dougal.s@gmail.com".freeze
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "CHANGELOG",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "base58.gemspec",
    "lib/base58.rb",
    "test/test_base58.rb"
  ]
  s.homepage = "http://github.com/dougal/base58".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.6".freeze
  s.summary = "Base58 is a Ruby library for converting ints or binaries to and from base58.".freeze
end

